language: node_js
node_js:
- '5'
branches:
  only:
  - "/^v[0-9]/"
after_success:
- npm run coverage
- npm run mocha:json
- bash <(curl -s https://codecov.io/bash)
- bash <(curl -s https://codecov.octoblu.com/bash)
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: gE6OmpOCkkeuw4/kWhSbuCIdllolItjubssn0zhNR5fIMlVcRlpHe2kp4TFde/Ggd0+M7DmNvNzUycqT6N7nLzQFS1e5h6WbEISP4/vSHai9FZ3dQSSXKdPaxDYHhD0SeHTdz6FsLgBKT5CL2kg1B+96DJPC9D5JsvMb0LtKtaZdN+9FY8qvNSaFEv8yXvrQhZFUEFTP5DrNGZQ+CuEDZIe8cr5x8J6/4QJXMPpTa9CwNj4FqUvpawlPlVA1mnf9k3FiIW180gebKUwsg2qHiN3GPMXd99wl1deCh18sq8HL9V5WVDvF+YAmK52Pg0T+GrCSP5gvJ+f89l9HRk/Y1xb57AexSbDSXVmeUHME4wiK4TPpGAdlvnXyJ+IxwsyBp45bNquJeWs5xNfRhhKSFN8gRqV8hzBj/RVLhEkh8WLzG/rVf+xBBiSMuQkBQcaCmKhlrNseLwZ7rY0K30ZRb2jsiJqbntMmSsElgwUblZzP5LS54J4t4map3aFPdxVO47wl+hEOj1X/3PdKPi7o6FrHpE2tPOmv9tmsjhPVyP1+GO290K0xF6T83XvLMvVrRF13xWMko7s7mkSFbuqQo24kgFDPa//8sT/UWtznn5r+0TK/aEtNfaQRObhulXuEuc+mX77cQ5FNeKYczDyaFCvJZS8m0GLReUutM9QbwZE=
  on:
    tags: true
    branches: true
